language: python

python:
  - 2.7
  - 3.2
  #- 3.4

branches:
    except:
        - gh-pages

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev libblas-dev liblapack-dev libatlas-base-dev gfortran #cython python-numpy python-scipy python3-numpy python3-scipy
   #- cython pyfftw/pyfftw.pyx
   #- cython pyfftw/utils.pxi

install: 
 - pip install cython
 - pip install numpy
 - pip install scipy
 - python setup.py build_ext --inplace

script: python setup.py test
